# Generated by Django 5.1.2 on 2025-05-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_job_owner',
        ),
    ]
